import "~/styles/globals.css";

import { type Metadata } from "next";
import { Lato } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import HeroProvider from "~/heroProvider";

export const metadata: Metadata = {
  title: "AstralFantasia",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Lato({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-geist-sans",
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable} h-full`}>
      <body className="bg-[url(backgrounds/teamBuilder.png) h-full">
        <TRPCReactProvider>
          <HeroProvider>{children}</HeroProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
